version: '3.8'

services:
  # Serviço de Banco de Dados (PostgreSQL)
  fiap-tech-challenger-fase2-db:
    hostname: fiap-tech-challenger-fase2-db
    image: postgres:15
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5433:5432"
    volumes:
      - fiap-tech-challenger-fase2-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d products_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço de Backend de Produtos
  fiap-tech-challenger-fase2-products-service:
    hostname: fiap-tech-challenger-fase2-products-service
    network_mode: host
    extends:
      file: products-service/docker-compose.yml
      service: app
    volumes:
      - fiap-tech-challenger-fase2-products-service:/app/media

  # Serviço de Backend de Otimização
  fiap-tech-challenger-fase2-optimizer-cargo-service:
    hostname: fiap-tech-challenger-fase2-optimizer-cargo-service
    network_mode: host
    extends:
      file: optimizer-cargo-service/docker-compose.yml
      service: app
    volumes:
      - fiap-tech-challenger-fase2-optimizer-cargo-service:/app/media

  # Serviço de Frontend Streamlit
  fiap-tech-challenger-fase2-products-frontend:
    hostname: fiap-tech-challenger-fase2-products-frontend
    network_mode: host
    extends:
      file: products-frontend/docker-compose.yml
      service: app
    volumes:
      - fiap-tech-challenger-fase2-products-frontend:/app/media


volumes:
  fiap-tech-challenger-fase2-db:
  fiap-tech-challenger-fase2-products-service:
  fiap-tech-challenger-fase2-optimizer-cargo-service:
  fiap-tech-challenger-fase2-products-frontend:
