version: '3'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt
    environment:
      - API_URL=http://products-service:8000/products
      - OPTIMIZER_URL=http://optimizer-service:8002/optimize/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

